### ISSUE TITLE
Lmao

### ISSUE THREAD

**Issue by zixenn** [ReCreatedOS/rec-sPsGui#1]
why you need this when you have nmap lul?

**Comment by ReCreatedOS** [comment]
I dont need that, Its just for people who is not good at scanning ports on terminal. Also for understanding python more.

**Comment by zixenn** [comment]
Okay, I understand you now. But you need to come to discord now.

recreatedos ***@***.***>, 28 Nis 2023 Cum, 18:28 tarihinde
şunu yazdı:
